# 安装提交前自检钩子 .git/hooks/pre-commit
# 效果: 每次 git commit 前自动运行 run_tests.ps1 统一门禁，
#       红灯（任一测试套件失败 / 前端 tsc 报错）时以非零退出中止本次提交。
# 用法: powershell -ExecutionPolicy Bypass -File install_git_hooks.ps1
# 临时跳过（例如仅改文档）: 先设环境变量 $env:CI_SKIP = "1" 再 git commit
$ErrorActionPreference = "Stop"
$root = Split-Path -Parent $MyInvocation.MyCommand.Path
$hooksDir = Join-Path $root ".git\hooks"
if (-not (Test-Path $hooksDir)) {
    Write-Host "未找到 $hooksDir —— 请确认当前目录是 git 仓库根（含 .git 目录）" -ForegroundColor Red
    exit 1
}

$hookPath = Join-Path $hooksDir "pre-commit"
# 注意: 钩子由 Git 内嵌 bash(sh) 执行，正文必须保持纯 ASCII
$hookContent = @'
#!/bin/sh
# Pre-commit CI gate (auto-generated by install_git_hooks.ps1; do not edit by hand)
# Runs run_tests.ps1 (full test gate). Non-zero exit aborts the commit.
# Temporarily skip with env var: CI_SKIP=1
[ -n "$CI_SKIP" ] && exit 0
cd "$(dirname "$0")/../.." || exit 1
exec powershell.exe -NoProfile -ExecutionPolicy Bypass -File ./run_tests.ps1
'@
Set-Content -Path $hookPath -Value $hookContent -Encoding ascii -Force
Write-Host "已安装提交前钩子: $hookPath" -ForegroundColor Green
Write-Host "之后每次 git commit 都会先跑全量门禁；需临时跳过时设置环境变量 CI_SKIP=1"
